name: Build Java
on: [push, pull_request]
jobs:
  build-jdk8:
    runs-on: ubuntu-latest
    name: Build Java 8 Projects
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
